pipeline {

  agent any

  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
  }

  stages {

    stage('Build') {

      steps {
        sh 'docker build -t killerbee7/Jenkins_Docker:latest .'
      }
    }

    stage('Login') {

      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }

    stage('Push') {

      steps {
        sh 'docker push killerbee7/Jenkins_Docker:latest'
      }
    }
  }

  post {
    always {
      sh 'docker logout'
    }
  }

}